name: deploy-app

inputs:
  env_name:
    required: true
  port:
    required: true

runs:
  using: composite
  steps:
    - shell: powershell
      run: echo "get app"

    - uses: actions/download-artifact@v4
      with:
        name: python-greetings-app
        path: python-greetings

    - shell: powershell
      run: echo "deploy ${{ inputs.env_name }}"

    - shell: powershell
      continue-on-error: true
      run: pm2 delete greetings-app-${{ inputs.env_name }}

    - shell: powershell
      working-directory: python-greetings
      run: |
        $env:PORT = "${{ inputs.port }}"
        pm2 start app.py --name greetings-app-${{ inputs.env_name }} --interpreter venv\Scripts\python.exe