name: deploy-app

inputs:
  env_name:
    required: true
  port:
    required: true

runs:
  using: composite
  steps:
    - shell: powershell
      run: echo "get app"

    - shell: powershell
      run: |
        if (Test-Path "${{ runner.temp }}\python-greetings-${{ inputs.env_name }}") {
          Remove-Item -Recurse -Force "${{ runner.temp }}\python-greetings-${{ inputs.env_name }}"
        }

    - uses: actions/download-artifact@v4
      with:
        name: python-greetings-app
        path: ${{ runner.temp }}\python-greetings-${{ inputs.env_name }}

    - shell: powershell
      run: echo "deploy ${{ inputs.env_name }}"

    - shell: powershell
      continue-on-error: true
      run: pm2 delete greetings-app-${{ inputs.env_name }}

    - shell: powershell
      working-directory: ${{ runner.temp }}\python-greetings-${{ inputs.env_name }}
      run: |
        $env:PORT = "${{ inputs.port }}"
        pm2 start app.py --name greetings-app-${{ inputs.env_name }} --interpreter venv\Scripts\python.exe

    - shell: powershell
      run: pm2 list