name: python-greetings

on:
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo "install deps"
        shell: powershell

      - uses: ./.github/actions/install-pip-deps
        with:
          app_path: python-greetings

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - run: echo "deploy dev"
        shell: powershell

      - uses: ./.github/actions/deploy-app
        with:
          env_name: dev
          port: "7001"
          app_path: python-greetings

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - run: echo "test dev"
        shell: powershell

      - uses: ./.github/actions/run-tests
        with:
          env_name: dev
          tests_path: course-js-api-framework

  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - run: echo "deploy stg"
        shell: powershell

      - uses: ./.github/actions/deploy-app
        with:
          env_name: stg
          port: "7002"
          app_path: python-greetings

  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps:
      - run: echo "test stg"
        shell: powershell

      - uses: ./.github/actions/run-tests
        with:
          env_name: stg
          tests_path: course-js-api-framework

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - run: echo "deploy preprod"
        shell: powershell

      - uses: ./.github/actions/deploy-app
        with:
          env_name: preprod
          port: "7003"
          app_path: python-greetings

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - run: echo "test preprod"
        shell: powershell

      - uses: ./.github/actions/run-tests
        with:
          env_name: preprod
          tests_path: course-js-api-framework

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - run: echo "deploy prod"
        shell: powershell

      - uses: ./.github/actions/deploy-app
        with:
          env_name: prod
          port: "7004"
          app_path: python-greetings

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - run: echo "test prod"
        shell: powershell

      - uses: ./.github/actions/run-tests
        with:
          env_name: prod
          tests_path: course-js-api-framework